### PR TITLE
Add list.dirs for R < 2.13

### PR DESCRIPTION
**Pull request by rtirrell**
Other than that (and the use of [-1] in mod.dates<-do.call(rbind, lapply(mobile.files[-1], file.info))), it works fine on R2.12. I just changed the lazy-load version check to only check < 2.12 and added list.dir if the version is < 2.13. I didn't change the warning message.

### CODE REVIEW

**Comment by drewconway** [comment]
Awesome, I will merge this patch in.

**Comment by rtirrell** [comment]
I'm not sure why mod.dates is using mobile.files[-1], this breaks stalkR for me, but I didn't touch it - I figured there must be a good reason.

**Comment by drewconway** [comment]
The first element of that array is to the parent folder, so I skip it.

**Comment by rtirrell** [comment]
Ahhh, okay - the list.files/file_test approach doesn't also give you the parent. So this is an incomplete patch. You could just abandon list.dirs, which seems to be the only 2.13 requirement.

**Comment by rtirrell** [comment]
This drops the 2.13 dependency and includes an updated package - seems to work fine for me!

**Pull request merged**
